services:
  rest_api:
    container_name: rest_api
    build: .
    command: bash -c "rm -f rest_api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rest_api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: rest_api_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
